framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    serializer:
        serialize_null: true
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: '^/', host: "127.0.0.1", fallback_format: json, priorities: [ json ] }